### ISSUE TITLE
Support "see" links in frontmatter

### ISSUE THREAD

**Issue by deviantintegral** [Lullabot/gatsby-theme-adr#39]
**Is your feature request related to a problem? Please describe.**

When deprecating an ADR, it can be useful to link to more current references. For example, if a single ADR is split into multiple ADRs, it would make sense to link to a related tag.

**Describe the solution you'd like**

Support the following in the frontmatter:

```
see:
  - text: the url text
    href: the url link
  - text: the second url text
    href: the second url link
```

**Describe alternatives you've considered**

The initial take was `see: <href>` but @e0ipso suggested supporting multiple links would be more future proof.

**Additional context**

As a workaround, we can simply edit the main body text.
